=== Mount-Skete/orthodox-typikon-feasts-xml/schemas/feasts.xsd
<?xml version='1.0' encoding='utf-8'?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified" version="1.0">

  <xsd:element name="feasts">
    <xsd:annotation>
      <xsd:documentation>
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="feast" type="FeastType" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="FeastType">
    <xsd:sequence>
      <xsd:element name="refs" type="RefsType" minOccurs="0" maxOccurs="1" />
      <xsd:element name="title" type="TitleType" minOccurs="1" maxOccurs="1" />
      <xsd:element name="date" type="DateType" minOccurs="1" maxOccurs="1" />
      <xsd:element name="hymns" type="HymnsType" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string" />
    <!-- TODO:-->
    <xsd:attribute name="type" type="xsd:string" />
    <xsd:attribute name="rank" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="RefsType">
    <xsd:sequence>
      <xsd:element name="ref" type="RefType" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="RefType">
    <xsd:attribute name="id" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="TitleType">
    <xsd:sequence>
      <xsd:element name="ru" type="TextContentType" minOccurs="0" maxOccurs="1" />
      <xsd:element name="cu" type="TextContentType" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ContentType">
    <xsd:sequence>
      <xsd:element name="ru" type="TextContentType" minOccurs="0" maxOccurs="1" />
      <xsd:element name="cu" type="TextContentType" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name="TextContentType">
    <xsd:restriction base="xsd:string" />
  </xsd:simpleType>

  <xsd:complexType name="DateType">
    <xsd:sequence>
      <xsd:element name="julian" type="JulianDateType" minOccurs="0" maxOccurs="1" />
      <xsd:element name="easter" type="EasterDateType" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name="JulianDateType">
    <xsd:restriction base="xsd:string">
      <xsd:minLength value="5" />
      <xsd:maxLength value="5" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="EasterDateType">
    <xsd:attribute name="days" type="EasterDateDaysType"/>
  </xsd:complexType>

  <xsd:simpleType name="EasterDateDaysType">
    <xsd:restriction base="xsd:nonNegativeInteger"/>
  </xsd:simpleType>

  <xsd:complexType name="HymnsType">
    <xsd:sequence>
      <xsd:element name="hymn" type="HymnType" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="HymnType">
    <xsd:sequence>
      <xsd:element name="title" type="TitleType" minOccurs="1" maxOccurs="1" />
      <xsd:element name="content" type="ContentType" minOccurs="1" maxOccurs="1" />
    </xsd:sequence>
    <xsd:attribute name="type" type="HymnClassType" />
    <xsd:attribute name="echo" type="HymnEchoType" />
  </xsd:complexType>

  <xsd:simpleType name="HymnClassType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="troparion" />
      <xsd:enumeration value="kontakion" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="HymnEchoType">
    <xsd:restriction base="xsd:nonNegativeInteger">
      <xsd:maxInclusive value="8" />
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== Mount-Skete/orthodox-typikon-feasts-xml/typikon-feasts-ru/feasts_01.xml
<?xml version='1.0' encoding='utf-8'?>
<feasts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schemas/feasts.xsd">
    <feast id="" type="great" rank="vigil">
        <refs>
            <ref id="ls-128-1" />
        </refs>
        <title>
            <ru>Еже по плоти Обрезание Господа Бога и Спаса нашего Иисуса Христа</ru>
        </title>
        <date>
            <julian>01-01</julian>
        </date>
        <hymns>
            <hymn type="kontakion" echo="3">
                <title>
                    <ru>Кондак праздника, глас 3</ru>
                </title>
                <content>
                    <ru>
                        Всех Господи
                        обрезание терпит, и человеческая прегрешения яко благ обрезует, дает
                        спасение днесь миру: радуется же в вышних и создателев
                        иерарх и светоносный, божественный таинник Христов Василий.
                    </ru>
                </content>
            </hymn>
        </hymns>
    </feast>

    <feast id="" type="low" rank="ordinary">
        <refs>
            <ref id="ls-128-2" />
        </refs>
        <title>
            <ru>Память иже во святых отца нашего Василиа великаго, архиепископа кесарии
                каппадокийския</ru>
        </title>
        <date>
            <julian>01-01</julian>
        </date>
        <hymns>
            <hymn type="troparion" echo="1">
                <title>
                    <ru>Тропарь святаго, глас 1</ru>
                </title>
                <content>
                    <ru>
                        Во всю землю
                        изыде вещание твое, яко приемшую слово твое, имже боголепно научил еси,
                        естество сущих уяснил еси, человеческия обычаи украсил еси, царское
                        священие, отче преподобне: моли Христа Бога спастися душам нашим.
                    </ru>
                </content>
            </hymn>
            <hymn type="kontakion" echo="4">
                <title>
                    <ru>Кондак, святаго, глас 4</ru>
                </title>
                <content>
                    <ru>
                        Явился еси основание непоколебимое
                        церкве, подая всем некрадомое господьство человеком, запечатлея твоими
                        веленьми, небоявленне Василие преподобне.
                    </ru>
                </content>
            </hymn>
        </hymns>
    </feast>

    <feast id="" type="low" rank="ordinary">
        <title>
            <ru>Предпразднство Просвещения</ru>
        </title>
        <date>
            <julian>01-02</julian>
        </date>
        <hymns>
            <hymn type="kontakion" echo="4">
                <title>
                    <ru>Кондак предпразднства, глас 4</ru>
                </title>
                <content>
                    <ru>
                        Во струях днесь иорданских быв Господь,
                        Иоанну вопиет: не убойся крестити мя: спасти бо приидох Адама
                        первозданнаго.
                    </ru>
                </content>
            </hymn>
        </hymns>
    </feast>

    <feast id="" type="low" rank="ordinary">
        <refs>
            <ref id="ls-129-2" />
        </refs>
        <title>
            <ru>Память во святых отца нашего Силвестра, папы римскаго</ru>
        </title>
        <date>
            <julian>01-02</julian>
        </date>
        <hymns>
        </hymns>
    </feast>

    <feast id="" type="middle" rank="vigil">
        <refs>
            <ref id="ls-129-1" />
        </refs>
        <title>
            <ru>Преставление преподобнаго отца нашего Серафима Саровскаго</ru>
        </title>
        <date>
            <julian>01-02</julian>
        </date>
        <hymns>
            <hymn type="troparion" echo="4">
                <title>
                    <ru>Тропарь, глас 4</ru>
                </title>
                <content>
                    <ru>
                        От юности Христа
                        возлюбил еси блаженне, и тому единому работати пламенне вожделев,
                        непрестанною молитвою и трудом пустыни подвизался еси, умиленным же
                        сердцем любовь Христову стяжав, избранник возлюблен Божия Матере явился
                        еси. сего ради вопием ти: спасай нас молитвами твоими, Серафиме,
                        преподобне отче наш.
                    </ru>
                </content>
            </hymn>
            <hymn type="kontakion" echo="2">
                <title>
                    <ru>Кондак, глас 2</ru>
                </title>
                <content>
                    <ru>
                        Мира красоту и яже в нем
                        тленная оставив, преподобне, в саровскую обитель вселился еси: и тамо
                        ангельски пожив, многим путь был еси ко спасению: сего ради и Христос
                        тебе, отче Серафиме, прослави и даром исцелений и чудес обогати. темже
                        вопием ти: радуйся, Серафиме, преподобне отче наш.
                    </ru>
                </content>
            </hymn>
        </hymns>
    </feast>

    <feast id="" type="low" rank="ordinary">
        <title>
            <ru>Предпразднство Просвещения</ru>
        </title>
        <date>
            <julian>01-03</julian>
        </date>
        <hymns>
        </hymns>
    </feast>

    <feast id="" type="low" rank="ordinary">
        <refs>
            <ref id="ls-130-2" />
        </refs>
        <title>
            <ru>Святаго пророка Малахиа</ru>
        </title>
        <date>
            <julian>01-03</julian>
        </date>
        <hymns>
            <hymn type="kontakion" echo="4">
                <title>
                    <ru>Кондак пророка, глас 4</ru>
                </title>
                <content>
                    <ru>
                        Пророчества дарованием богатея,
                        пророче, Христово предвозвестил еси пришествие яве, и мирови спасение,
                        егоже сиянием мир просветися.
                    </ru>
                </content>
            </hymn>
        </hymns>
    </feast>

    <feast id="" type="low" rank="ordinary">
        <refs>
            <ref id="ls-130-1" />
        </refs>
        <title>
            <ru>Святаго мученика Гордиа</ru>
        </title>
        <date>
            <julian>01-03</julian>
        </date>
        <hymns>
            <hymn type="kontakion" echo="8">
                <title>
                    <ru>Ин кондак мученика, глас 8</ru>
                </title>
                <content>
                    <ru>
                        Твоя поты, преславне, всю землю
                        напоиша, и честными кровьми, Гордие, мир весь возвеселил еси: молитвами
                        твоими Богомудре, спасай вся верою тя воспевающия и ублажающия, вопиющия
                        песнь достойную, всехвальне, яко многострадалец.
                    </ru>
                </content>
            </hymn>
        </hymns>
    </feast>

    <feast id="" type="low" rank="ordinary">
        <title>
            <ru>Предпразднство Просвещения</ru>
        </title>
        <date>
            <julian>01-04</julian>
        </date>
        <hymns>
        </hymns>
    </feast>

    <feast id="" type="low" rank="ordinary">
        <refs>
            <ref id="ls-131-1" />
        </refs>
        <title>
            <ru>Собор святых 70 апостолов</ru>
        </title>
        <date>
            <julian>01-04</julian>
        </date>
        <hymns>
            <hymn type="kontakion" echo="2">
                <title>
                    <ru>Кондак апостолов, глас 2</ru>
                </title>
                <content>
                    <ru>
                        Христовых учеников лик седмьдесят, божественно вернии в песнех
                        восхвалим: теми бо вси навыкохом Троицу почитати нераздельную, и
                        пребывают светильницы божественныя веры.
                    </ru>
                </content>
            </hymn>
        </hymns>
    </feast>

    <feast id="" type="low" rank="ordinary">
        <title>
            <ru>Преподобнаго отца нашего Феоктиста игумена, иже в Кукуме Сикелийстем</ru>
        </title>
        <date>
            <julian>01-04</julian>
        </date>
        <hymns>
        </hymns>
    </feast>

    <feast id="" type="low" rank="ordinary">
        <title>
            <ru>Предпразднство Просвещения</ru>
        </title>
        <date>
            <julian>01-05</julian>
        </date>
        <hymns>
            <hymn type="troparion" echo="4">
                <title>
                    <ru>Тропарь предпразднства, глас 4</ru>
                </title>
                <content>
                    <ru>
                        Возвращашеся иногда Иордан река милотию Елиссеовою, вознесшуся
                        Илии, и разделяхуся воды сюду и сюду, и бысть ему сух путь, иже мокрый,
                        во образ воистинну крещения, имже мы текущее жития преходим шествие:
                        Христос явися во Иордане освятити воды.
                    </ru>
                </content>
            </hymn>
            <hymn type="kontakion" echo="2">
                <title>
                    <ru>Кондак, глас 2</ru>
                </title>
                <content>
                    <ru>
                        Всех, Христе, благоутробне отемляй
                        прегрешений множество, милости ради безмерныя, Иорданскими водами
                        креститися грядеши яко человек, одеждею мя одевая, славы древния
                        обнаженна люте.
                    </ru>
                </content>
            </hymn>
        </hymns>
    </feast>

    <feast id="" type="low" rank="ordinary">
        <refs>
